---
name: Test-Builder-Mock-Class
version: 0.02
author:
  - 'Piotr Roszatycki <dexter@cpan.org>'
abstract: Simulating other classes for Test::Builder
license: lgpl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Test-Builder-Mock-Class
  license: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
  repository: https://dexter-cpan.googlecode.com/svn/Test-Builder-Mock-Class
requires:
  Test::Builder: 0
  Test::Mock::Class: 0.02
  namespace::clean: 0
  perl: 5.006
provides:
  Test::Builder::Mock::Class:
    file: lib/Test/Builder/Mock/Class.pm
    version: 0.02
  Test::Builder::Mock::Class::Role::Meta::Class:
    file: lib/Test/Builder/Mock/Class/Role/Meta/Class.pm
    version: 0.02
  Test::Builder::Mock::Class::Role::Object:
    file: lib/Test/Builder/Mock/Class/Role/Object.pm
    version: 0.02
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
